src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/domain/UserDTO.java
src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
src/main/java/com/theantiquersroom/myapp/service/UserService.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml

#8 회원가입 API구현 
회원가입 정보를 입력받아 데이터 베이스에 저장

회원가입 API 구현

---

src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
src/main/java/com/theantiquersroom/myapp/service/UserService.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/webapp/WEB-INF/views/users/get.jsp
src/main/webapp/WEB-INF/views/users/getUserList.jsp
src/main/webapp/WEB-INF/views/users/modify.jsp

Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: Error attempting to get column 'PHONE' from result set. Cause: java.sql.SQLException: Out of range value for column 'PHONE' : value 010-0000-0000
controller 클래스의 매핑메서드 안 객체를 DTO, VO 클래스 변수 순서에 맞게 다시 나열 했더니 오류해결 (코드에는 오류가 안떠서 찾기 힘들었다)
#28 회원 정보, 회원 수정

회원 정보, 회원 수정

---

pom.xml
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
src/test/java/com/theantiquersroom/myapp/pwhash/PasswordEncryptionTests.java

#23 회원가입시 비밀번호 암호화 
- pox.xml에 security 관련 maven추가
- BCryptPasswordEncoder를 이용하여 회원가입 시 받은 비밀번호를 암호화하여 DB에 저장
- 연관되어, 로그인 시 받는 비밀번호와 DB에 저장된 값 비교하여 로그인할 수 있도록 변경함 
비밀번호 암호화

Ggujin security password

---

pom.xml
src/main/java/com/theantiquersroom/myapp/controller/ApiKakaoController.java
src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/domain/KakaoAccountVO.java
src/main/java/com/theantiquersroom/myapp/domain/KakaoTokenVO.java
src/main/java/com/theantiquersroom/myapp/domain/KakaoUserInfoVO.java
src/main/java/com/theantiquersroom/myapp/domain/UserDTO.java
src/main/java/com/theantiquersroom/myapp/domain/UserVO.java
src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
src/main/java/com/theantiquersroom/myapp/service/UserService.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
src/main/webapp/WEB-INF/views/home.jsp

#27 
#39 
-카카오 로그인 시, 액세스 토큰을 통해 카카오계정 ID 가져오기
-ID 조회하여 비회원일 경우 회원가입 페이지로, 기존회원일 경우 메인페이지로 이동(현재 임시로 연결)
* login.jsp 완성되면 카카오 로그인페이지 버튼 연결 예정 @hayo01
* register.jsp 완성되면 참고하여 카카오 계정용 회원가입 페이지 추가 및 연결 예정 @subakibaksu

kakao login api

---

src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
src/main/java/com/theantiquersroom/myapp/service/UserService.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
src/main/webapp/WEB-INF/views/users/findId.jsp
src/main/webapp/WEB-INF/views/users/modify.jsp

아이디 찾기 , 회원삭제 

---

src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/service/UserService.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/java/com/theantiquersroom/myapp/utils/UserType.java
src/main/webapp/WEB-INF/views/home.jsp

#50 
ADMIN - 어드민
GENERAL - 일반
KAKAO - 카카오

UserType Enum 생성

---

src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
src/main/java/com/theantiquersroom/myapp/domain/QnADTO.java
src/main/java/com/theantiquersroom/myapp/mapper/BoardMapper.java
src/main/java/com/theantiquersroom/myapp/service/BoardService.java
src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/QnA.jsp
src/main/webapp/WEB-INF/views/board/registerQnA.jsp

#85
servlet.xml에 이거 추가해주세요! <beans:bean id="boardService" class="com.theantiquersroom.myapp.service.BoardService" abstract="true"/>

BoardQnA 다시 올립니다.

---

src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/resources/css/footer.css
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/main.css
src/main/webapp/resources/js/main.js

#99 
- footer.css >> position을 relative로 바꾸어 footer 탈착 현상 해결
- header.css >> width를 100%로 바꾸어 페이지 넘어가는 현상 해결
- main.css >> main페이지의 전반적인 css 적용    **script의 순서 매우 중요!**
- main.jsp 
>> 일률적인 div사용 대신, <header><footer>와 같이 명시적인 태그로 변경
>> 전체적인 틀 완성
>> 클릭 스크롤 기능 구현!! (scrollLeft : MDN참고)

update main page & header/footer of css

---

src/main/java/com/theantiquersroom/myapp/domain/ProductDTO.java
src/main/java/com/theantiquersroom/myapp/mapper/ProductMapper.java
src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/detail.jsp
src/test/java/com/theantiquersroom/myapp/mapper/ProductMapperTests.java
src/test/java/com/theantiquersroom/myapp/service/ProductServiceTests.java

#61 #62 
- ProductDTO >> List<String> imageUrls 추가
- ProductMapper.java/.xml >> getProductImageUrls 메소드 추가
- ProductServiceImpl >> mapper에 추가된 메소드 추가 구현
- ProductMapperTests, ProductServiceTests >> 추가된 메소드 테스트
- detail.jsp >> 이미지 불러오기 위한 el 추가
금일 전체 취합 우선 진행을 위해 Full Request

add GetProductImageUrls() into getDetail & update detailPage

---

src/main/webapp/WEB-INF/views/common/footer.jsp
src/main/webapp/WEB-INF/views/detail.jsp
src/main/webapp/resources/css/detail.css

#61 #62 
- detail.jsp에 header, footer 메인 페이지와 동일한 방식으로 적용
- jQuery를 사용하여 작은 이미지 클릭 시, 포커스 되어 큰 이미지로 볼 수 있도록 구현
- 클릭 가능한 버튼, 링크의 커서 모양 pointer 적용

Hayoung update detail page

---

src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
src/main/java/com/theantiquersroom/myapp/domain/ProductDTO.java
src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
src/main/java/com/theantiquersroom/myapp/service/AdminService.java
src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
src/main/webapp/WEB-INF/views/admin/requestedList.jsp
src/main/webapp/WEB-INF/views/common/footer.jsp
src/main/webapp/WEB-INF/views/users/myAuctionList.jsp
src/main/webapp/resources/css/footer.css
src/main/webapp/resources/css/myAuctionList.css

#126 
승인요청 반려 기능 추가 구현
-승인을 반려할 수 있도록 '승인반려'기능 추가
-다중 선택 후 '반려'버튼 클릭 시 ajax로 경매상태 바로 변경 반영
-정렬 조건 추가 : 승인대기중 > 완료 > 반려 순 + 글작성일 desc
-대표이미지 연결 추가
-현재가격(입찰 최고금액) 연결 추가
-원래 요구사항에 없는 부분이지만 승인을 안한 상품이 계속 승인대기중인 상태로 목록에 보이는 문제도 있어, 
'반려' 기능을 추가하게 됨. **경매상태 : '승인반려' 추가
-승인요청상품 리스트 모든 기능 구현되었으나, 제품 이미지 클릭하여 디테일이 toggle로 구현되는 부분에서
스크립트도 같이 출력되는 문제가 있어 해결 예정

승인요청 반려 기능 추가 구현

---

src/main/java/com/theantiquersroom/myapp/HomeController.java
src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
src/main/java/com/theantiquersroom/myapp/controller/RegisterController.java
src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/domain/ProductDTO.java
src/main/java/com/theantiquersroom/myapp/mapper/ProductMapper.java
src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
src/main/java/com/theantiquersroom/myapp/service/ProductService.java
src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
src/main/java/com/theantiquersroom/myapp/service/UserService.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
src/main/webapp/WEB-INF/views/detail.jsp
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/login.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/WEB-INF/views/register.jsp
src/main/webapp/WEB-INF/views/resetPwd.jsp
src/main/webapp/WEB-INF/views/users/myBidList.jsp
src/main/webapp/resources/css/productList.css
src/main/webapp/resources/css/resetPassword.css
src/main/webapp/resources/js/resetPassword.js

1.메인페이지 BE 완료,
2. resetPassword 로그인페이지에 삽입 +암호화
3. register페이지에 이메일 인증삽입, 
4. productList(이미지, 현재가격),
5. detail.jsp 현재가격 출력 
6. myBidList backend 진행중

resetPassword , comfirmEmail 등 분산된 기능 병합 및 메인페이지 BE완료

---

src/main/java/com/theantiquersroom/myapp/HomeController.java
src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
src/main/java/com/theantiquersroom/myapp/domain/UserVO.java
src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
src/main/java/com/theantiquersroom/myapp/service/AdminService.java
src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
src/main/webapp/WEB-INF/views/admin/userList.jsp
src/main/webapp/WEB-INF/views/common/adminHeader.jsp
src/main/webapp/resources/css/adminHeader.css
src/main/webapp/resources/css/userList.css
src/test/java/com/theantiquersroom/myapp/mapper/AdminMapperTests.java
src/test/java/com/theantiquersroom/myapp/service/AdminServiceTests.java

#134
- 회원 목록 조회 및 검색 기능 구현 : AdminController, AdminService, AdminMapper
- UserVO : ajax로 회원검색 요청시 필요한 정보만 받기 위해 사용
- AdminMapperTests : 회원 검색 mapper 테스트
- userList : 페이지 생성 및 UI구현, ajax를 이용한 검색 스크립트 추가
- adminHeader : UI 스타일 변경 - 폰트, 정렬, 로그아웃 버튼 위치 등
닉네임으로 회원을 검색하였을 때, 현재는 많은 결과를 가져올 일이 없어 티가 나지 않으나,
추후 한번에 많은 검색 결과가 나왔을 때에도 페이징이 가능하도록 하는 방법 논의 필요

add AdminUserList

---

src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
src/main/java/com/theantiquersroom/myapp/domain/ProductModifyDTO.java
src/main/java/com/theantiquersroom/myapp/mapper/ImageMapper.java
src/main/java/com/theantiquersroom/myapp/mapper/ProductMapper.java
src/main/java/com/theantiquersroom/myapp/service/ProductService.java
src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/ImageMapper.xml
src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/modify.jsp
src/main/webapp/resources/css/product/modify.css
src/test/java/com/theantiquersroom/myapp/mapper/ProductMapperTests.java
src/test/java/com/theantiquersroom/myapp/service/ProductServiceTests.java

#63 #64
- 코드정리
- Test
- 데이터 넘어오는거 보이는 뷰도 올렸습니다.
- 파일업로드 수정할때 지우고 새로넣기

product modify API

---

src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
src/main/java/com/theantiquersroom/myapp/domain/MypageCriteria.java
src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
src/main/java/com/theantiquersroom/myapp/service/AdminService.java
src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
src/main/webapp/WEB-INF/views/common/adminHeader.jsp
src/main/webapp/resources/css/myAuctionList.css

#130 
경매상품 키워드 조회 기능 구현
-닉네임, 상품명 키워드 조회
-동적쿼리 사용
-검색 결과 위한 페이징 별도 구현

어드민 경매상품 키워드 검색 기능 구현

---

src/main/webapp/WEB-INF/views/admin/userList.jsp
src/main/webapp/resources/css/userList.css

#134 
- userList.css >> 검색 창에 hover 시, 아래쪽 테이블의 위치가 미세하게 옮겨지는 것을 막기 위해 max-height 지정
- userList.jsp >> 회원 검색 결과 결과는 페이징 없이 스크롤 테이블 형태로 보여주도록, 페이징 div에 jQuery를 이용하여 hide() 설정

update result view of searchUser()

---

src/main/java/com/theantiquersroom/myapp/controller/LoginController.java
src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/interceptor/LoginInterceptor.java

delete @ResponseBody in logout()
#12 #14 #17 
- LoginController, LoginInterceptor >> 관리자 로그인 시, 관리자 메인 페이지로 넘어가도록 수정
- UserController >> logout 메소드에 @ResponseBody로 인해 로그아웃 이후 다음 페이지로 넘어가지 않아서 해당 어노테이션 삭제

update login interceptor for admin login

---

src/main/webapp/WEB-INF/views/users/mypage.jsp
src/main/webapp/resources/css/mypage.css

#72 #49 
- footer가  페이지에 맞지 않게 위치한 부분 수정
- \<body\> 태그 안의 content 재정렬
- 수정, 탈퇴버튼 모양 수정

update mypage UI

---

src/main/webapp/WEB-INF/views/product/modify.jsp
src/main/webapp/resources/css/product/modify.css

product modify view 파일업로드, 레이아웃 수정

---

src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/domain/MypageCriteria.java
src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
src/main/java/com/theantiquersroom/myapp/service/AdminService.java
src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
src/main/webapp/WEB-INF/views/registerByKakao.jsp

#131 
동적쿼리 이용하여 전체리스트, 키워드검색, 필터조회 기능 구현

관리자 경매상품 필터 기능 구현

---

src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
src/main/java/com/theantiquersroom/myapp/domain/ProductReRegisterDTO.java
src/main/java/com/theantiquersroom/myapp/mapper/ProductMapper.java
src/main/java/com/theantiquersroom/myapp/service/ProductService.java
src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml

#37 
- 유찰된 물품 가격 -10%하여 DB 등록
- 시작 시간은 현재시간
- 마감 시간은 현재시간 + 7DAY

product reRegister API 구현

---

src/main/java/com/theantiquersroom/myapp/Eception/CommonExceptionAdvice.java
src/main/webapp/WEB-INF/views/error/errorPage.jsp

#146 
- throws Exception로 던진 에러를 잡아서 보여줌
- test view 추가, front 작업 후 수정예정!

Exception API 구현, 간단한 test view

---

src/main/webapp/WEB-INF/views/common/footer.jsp
src/main/webapp/WEB-INF/views/register.jsp
src/main/webapp/resources/css/footer.css
src/main/webapp/resources/css/register.css
src/main/webapp/resources/js/registerCheck.js

#157 #155 
- Sweet alert 2적용 >> footer.jsp와 css파일에 적용 -> footer가 모든 페이지에 include되기 때문!
- 회원가입페이지 UI 수정 >> register.jsp, register.css

add SweetAlert2(in footer), update UserRegister UI

---

src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/main.jsp

#164 
경매종료된 상품이 ProductList, Main.jsp에서 출력되지않도록 수정했습니다.

종료된 상품 화면 출력 하지않도록 수정

---

src/main/webapp/WEB-INF/views/detail.jsp
src/main/webapp/resources/css/detail.css
src/main/webapp/resources/css/footer.css

#162 
- detail 페이지 내의 infoTable 관련 css 수정
- bidBtn 클릭 시, 발생하는 이벤트의 결과를 Sweet alert을 사용하여 보여줌

#162 issue_update bidBtn event in detail page

---

src/main/webapp/WEB-INF/views/product/productList.jsp

카테고리명과 화면이 일치하지 않는 이슈 해결
카테고리명과 화면이 일치하지 않는 이슈를 해결했습니다.

카테고리명과 화면이 일치하지 않는 이슈 해결

---

src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/resources/css/main.css

change main Banner img

---

src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/resources/css/main.css
src/main/webapp/resources/css/productList.css

#170 
- float으로 정렬되어있던 상품 리스트 -> grid로 정렬방식 변경
- flex를 이용한 헤더, 푸터 정렬

fix productList page_change to Grid

---

src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
src/main/webapp/WEB-INF/views/admin/requestedList.jsp
src/main/webapp/resources/css/myAuctionList.css

#128 
-이미지 클릭 시 디테일에 스크립트 보이는 오류 수정
-슬라이드 토글 시, 이미지 하단에 1열로만 생성하던 문제 -> tbody로 colspan으로 열병합하여 해결 
Thanks to @beomsookim96  :D

어드민 상품목록 디테일 버그수정

---

src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/WEB-INF/views/users/myBidList.jsp

Search product

---

src/main/java/com/theantiquersroom/myapp/domain/ProductCriteria.java
src/main/webapp/resources/css/header.css

SeachBar Change, ProductCriteria Modify 9 >> 12
서치바 CSS 개선, 출력 상품개수 9 >> 12

SeachBar Change, ProductCriteria Modify 9 >> 12

---

src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
src/main/java/com/theantiquersroom/myapp/domain/BoardReviewCriteria.java
src/main/java/com/theantiquersroom/myapp/domain/ProductDTO.java
src/main/java/com/theantiquersroom/myapp/domain/ReviewDTO.java
src/main/java/com/theantiquersroom/myapp/domain/ReviewImageDTO.java
src/main/java/com/theantiquersroom/myapp/domain/ReviewPageMakeDTO.java
src/main/java/com/theantiquersroom/myapp/mapper/BoardMapper.java
src/main/java/com/theantiquersroom/myapp/service/BoardService.java
src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
src/main/webapp/WEB-INF/views/admin/requestedList.jsp
src/main/webapp/WEB-INF/views/board/registerReview.jsp
src/main/webapp/WEB-INF/views/board/review.jsp
src/main/webapp/WEB-INF/views/detail.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/WEB-INF/views/users/myAuctionList.jsp
src/main/webapp/WEB-INF/views/users/myBidList.jsp
src/main/webapp/resources/css/review.css

#173 
- 부분적인 ${pId} , ${pid}로 수정 (전체는 추후에 잡아야할듯)
- 리뷰작성, 리뷰게시판 뷰페이지 구현
- 작성한 리뷰 DB에 전달
-

add Review 작성 기능 구현, DB 연결

---

src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/product/productList.jsp

#179 
메인페이지, 상세페이지 ${pId} >> ${pid} 로 수정

자바빈즈규약 위배 조건 수정

---

src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/resources/css/footer.css
src/main/webapp/resources/js/registerCheck.js

#181 이슈 참조

---

src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
src/main/webapp/WEB-INF/views/register.jsp
src/main/webapp/resources/js/registerCheck.js

#183 
- 회원가입 alert 문구 수정
- 회원가입 시, 메인으로 이동되지 않는 부분 해결
- 이전 master-merged 되었으나 컨플릭 해결하며 문제 발생되었던, BoardController파일 함께 수정

fix registerCheck, BoardController

---

src/main/java/com/theantiquersroom/myapp/controller/LoginController.java
src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/webapp/WEB-INF/views/users/modify.jsp
src/main/webapp/resources/css/modify.css

- LoginController, UserController, UserServiceImpl 파일에 있는 log제거
- 회원정보수정페이지 UI 수정 >> footer, button

delete log, fix modify_User UI

---

src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java

#186 
-> 회원 정보 수정 시, 새로 받은 비밀번호 암호화하여 DB에 저장
반드시 비밀번호 입력하도록, 추후 Front단에서 alert을 띄워줄 예정

fix #186 issue

---

src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/modify.jsp
src/main/webapp/WEB-INF/views/product/register.jsp

#190 
product의 reigster, modify 수정

product register, modify 수정

---

src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
src/main/java/com/theantiquersroom/myapp/domain/BoardQnACriteria.java
src/main/java/com/theantiquersroom/myapp/domain/QnADTO.java
src/main/java/com/theantiquersroom/myapp/domain/QnAPageMakeDTO.java
src/main/java/com/theantiquersroom/myapp/domain/ReviewDTO.java
src/main/java/com/theantiquersroom/myapp/service/BoardService.java
src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/QnA.jsp
src/main/webapp/WEB-INF/views/board/getQnADetail.jsp
src/main/webapp/WEB-INF/views/board/modifyQnA.jsp
src/main/webapp/WEB-INF/views/board/registerQnA.jsp
src/main/webapp/WEB-INF/views/board/registerReQnA.jsp
src/main/webapp/WEB-INF/views/common/mypageHeader.jsp
src/main/webapp/WEB-INF/views/detail.jsp
src/test/java/com/theantiquersroom/myapp/mapper/BoardMapperTests.java

BoardQnA pId -> pid 수정

---

src/main/java/com/theantiquersroom/myapp/controller/ApiKakaoController.java
src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/webapp/WEB-INF/views/registerByKakao.jsp

카카오 회원가입, 로그인, 로그아웃 업데이트
-회원가입 수정 적용
-로그인, 로그아웃 연결 마무리

카카오 회원가입, 로그인, 로그아웃 업데이트

---

src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/product/modify.jsp
src/main/webapp/WEB-INF/views/product/register.jsp

product register modify (sweet alert추가)

---

src/main/java/com/theantiquersroom/myapp/controller/UserController.java

delete alert 띄우기
추후 delete 보완 구현

delete alert 띄우기

---

src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
src/main/webapp/WEB-INF/views/board/QnA.jsp
src/main/webapp/WEB-INF/views/detail.jsp

pId >> pid
pId >> pid
detail 입찰 부분 FE수정중

pId >> pid

---

src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/product/modify.jsp
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/WEB-INF/views/product/register.jsp

#199 
- #199 이슈관련 수정 
- 상품등록 오류나서 원인 확인결과 pid 매퍼 수정

product category 변경사항 적용, pid오류 -> 매퍼수정

---

src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml

#189 #188 
상품승인여부 매퍼 반영 , 상품필터 현재가 기준으로 변경

출력상품에 상품승인여부 조건 추가, 상품필터 수정

---

src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
src/main/webapp/WEB-INF/views/board/QnA.jsp
src/main/webapp/WEB-INF/views/board/getQnADetail.jsp
src/main/webapp/WEB-INF/views/board/modifyQnA.jsp
src/main/webapp/WEB-INF/views/board/registerQnA.jsp
src/main/webapp/WEB-INF/views/board/registerReQnA.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/resources/css/QnA.css
src/main/webapp/resources/css/modifyQnA.css

boardQnAVeiw_JS

---

src/main/webapp/WEB-INF/views/board/QnA.jsp
src/main/webapp/resources/css/QnA.css
src/main/webapp/resources/css/review.css

#205 
상품상세 페이지의 문의사항 리스트 페이지 UI 수정

update QnA list page UI

---

src/main/java/com/theantiquersroom/myapp/controller/ApiKakaoController.java
src/main/java/com/theantiquersroom/myapp/controller/RegisterController.java
src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
src/main/webapp/WEB-INF/views/register.jsp
src/main/webapp/WEB-INF/views/registerByKakao.jsp
src/main/webapp/resources/css/register.css
src/main/webapp/resources/js/registerCheck.js

일반회원가입, 카카오회원가입 중복키 이슈 해결, Form제출을 Ajax방식으로 변경

---

src/main/webapp/WEB-INF/views/users/myBidList.jsp

mybidList -> 리뷰작성 path 수정

---

src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
src/main/webapp/WEB-INF/views/product/modify.jsp
src/main/webapp/WEB-INF/views/product/register.jsp
src/main/webapp/WEB-INF/views/register.jsp

- pId -> pid 변경
- 회원가입 button 변경
- 상품 등록,수정 경로 변경

pId -> pid 변경, 회원가입 button 변경, 상품 등록,수정 경로 변경

---

src/main/webapp/WEB-INF/views/detail.jsp

#225 
세션값 유무에 따라 입찰 실패 이후 경로 설정

update detail script

---

src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/resources/css/main.css

change main Banner imgs

---

src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/product/modify.jsp
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/WEB-INF/views/product/register.jsp

쇼파 -> 소파 명칭 변경(표준어)

---

src/main/java/com/theantiquersroom/myapp/controller/UserController.java
src/main/webapp/WEB-INF/views/users/chat.jsp
src/main/webapp/WEB-INF/views/users/myAuctionList.jsp
src/main/webapp/WEB-INF/views/users/myBidList.jsp

나의옥션 판매자 chat 연결

---

src/main/webapp/WEB-INF/views/board/getQnADetail.jsp

BoardQnA 답글버튼 오류 수정

---

src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
src/main/java/com/theantiquersroom/myapp/mapper/BoardMapper.java
src/main/java/com/theantiquersroom/myapp/service/BoardService.java
src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/registerReview.jsp
src/main/webapp/WEB-INF/views/board/review.jsp
src/main/webapp/resources/css/registerReview.css

- 리뷰리스트 전체 띄우는 것 -> 해당 판매자에 대한 리뷰만 띄워줌
- ㄴ 리뷰수정

판매자의 이전 리뷰 뷰페이지 수정, 쿼리수정, 리뷰페이지 이름수정

---

src/main/webapp/WEB-INF/views/common/adminHeader.jsp
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/login.jsp
src/main/webapp/WEB-INF/views/register.jsp
src/main/webapp/WEB-INF/views/users/modify.jsp
src/main/webapp/resources/css/adminHeader.css
src/main/webapp/resources/css/login.css
src/main/webapp/resources/css/modify.css
src/main/webapp/resources/css/mypage.css
src/main/webapp/resources/css/register.css

change User pages UI

---

src/main/java/com/theantiquersroom/myapp/controller/ProductController.java

product modify 경로 수정

---

src/main/webapp/WEB-INF/views/admin/requestedList.jsp

admin 승인요청페이지 - sweet alert sub text removed

sweet alert sub text removed

---

src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/resources/css/productList.css

Paging li 태그
Paging li 태그 , 정렬바로되게 수정

Paging li 태그

---

src/main/webapp/WEB-INF/views/users/myAuctionList.jsp

나의경매리스트 버튼명 변경, pId->pid 수정
